'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CadastroImovel

    '''<summary>
    '''mtwImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mtwImovel As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''vwCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwCadastro As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipoNegocio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoNegocio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCidade As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBairro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEnderenco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnderenco As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlTipoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoImovel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoMaterial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValor As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtValorCondominio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorCondominio As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtAreaConstruida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaConstruida As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtAreaTerreno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaTerreno As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtQtdeDormitorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeDormitorio As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtQtdeSuite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeSuite As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtQtdeBanheiro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeBanheiro As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtQtdeSala control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeSala As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtQtdeGaragem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeGaragem As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''InCozinha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InCozinha As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InCopa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InCopa As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InPiscina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InPiscina As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InAreaServico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InAreaServico As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InDependenciaEmpregada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InDependenciaEmpregada As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InChurrasqueira control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InChurrasqueira As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InCloset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InCloset As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InAdega control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InAdega As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InAreaFesta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InAreaFesta As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InAreaJogos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InAreaJogos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InLareira control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InLareira As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InSacada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InSacada As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InEscritorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InEscritorio As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InGasCentral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InGasCentral As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InPortaoEletronico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InPortaoEletronico As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InMobiliado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InMobiliado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InLancamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InLancamento As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InCobertura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InCobertura As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InPronto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InPronto As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InPorteiroEletronico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InPorteiroEletronico As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InLavabo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InLavabo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InTerraco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InTerraco As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDescricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescricao As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCondicaoVenda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCondicaoVenda As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''InDestaque control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InDestaque As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InPublicar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InPublicar As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtDataFechamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFechamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGravar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLimpar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcluir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vwFotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwFotos As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''uplFoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplFoto As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnEnviarFoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviarFoto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnExcluirFotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExcluirFotos As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dtgFotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgFotos As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnFinalizarFotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinalizarFotos As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''vwFinalizacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vwFinalizacao As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''lblImovelId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblImovelId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnNovoCadastro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovoCadastro As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As WebImoveis.Admin
        Get
            Return CType(MyBase.Master, WebImoveis.Admin)
        End Get
    End Property
End Class
