'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Consulta

    '''<summary>
    '''txtReferencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReferencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCidade As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''pnlBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBairro As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlBairro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBairro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoImovel As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlTipoMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoMaterial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtValorDe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorDe As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtValorAte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorAte As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''btnAbrirBuscaAvancada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAbrirBuscaAvancada As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divBuscaAvancada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBuscaAvancada As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cblBairros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblBairros As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''txtQtdeDomitorio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeDomitorio As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtQtdeSuite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeSuite As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtAreaConstruideDe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaConstruideDe As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''txtAreaConstruideAte control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaConstruideAte As Global.Utilitarios.WebComponents.CampoNumerico

    '''<summary>
    '''cblItensImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblItensImovel As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''btnAbrirBuscaBasica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAbrirBuscaBasica As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divTotalRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTotalRegistro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotalRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dtgImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgImovel As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As WebImoveis.Site
        Get
            Return CType(MyBase.Master, WebImoveis.Site)
        End Get
    End Property
End Class
