'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MeusImoveis

    '''<summary>
    '''divTotalRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTotalRegistro As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTotalRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalRegistro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dtgImovel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgImovel As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As WebImoveis.Site
        Get
            Return CType(MyBase.Master, WebImoveis.Site)
        End Get
    End Property
End Class
